version: "3.9"

services:
  flask:
    build:
      context: .
    ports:
      - "80:5000"
    volumes:
      - ./templates:/templates
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo: